name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - released
      - prereleased

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./vrp-cli
          target: ${{ matrix.target }}
          sccache: "true"
          args: --release --out dist -m Cargo.toml -i 3.12
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.target }}
          path: ./vrp-cli/dist
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [aarch64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "arm64"
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: ./vrp-cli
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: "true"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.target }}
          path: ./vrp-cli/dist

  gh-publish:
    name: Publish artifacts to GH
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: [linux, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
      - name: List artifacts
        run: ls -lhs
      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: ./*
